from conans import ConanFile, CMake, tools
from conans.tools import download, unzip
import os, re

class CeresSolverConan(ConanFile):
    name = "ceres-solver"
    version = "2.0.0"
    license = "New BSD"
    url = "https://github.com/ceres-solver/ceres-solver/"
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake_paths"
    requires = "eigen/3.3.7@conan/stable", "glog/0.4.0@bincrafters/stable", "gflags/2.2.2@bincrafters/stable"
    build_policy    = 'missing'
    options         = {
        'shared': [True, False],
        'fPIC':   [True, False],
        'cxx11':  [True, False],
        'suitesparse': [True, False],
        'cxsparse':    [True, False],
        'blas':        ['openblas', 'blas', 'custom', 'system'], # System basically doesn't do anything which should search system paths
    }
    default_options = (
        'shared=False',
        'fPIC=True',
        'cxx11=True',
        'suitesparse=False',
        'cxsparse=False',
        'blas=custom',
    )


    def source(self):
        # zip_name = self.version+".zip"
        # download("https://github.com/ceres-solver/ceres-solver/archive/"+self.version+".zip", zip_name)
        # unzip(zip_name)
        git = tools.Git(folder="ceres-solver-"+self.version)
        git.clone("https://github.com/ceres-solver/ceres-solver.git")
        git.checkout("edb8322bdabef336db290be1cc557145b6d4bf80")
        self.run("cd ceres-solver-" +self.version + " && git status")

        # 47e784bb4146da52d3b0695877326d60c36ab189 worked
        # edb8322bdabef336db290be1cc557145b6d4bf80 newest

    def build(self):
        cmake = CMake(self)
        cmake.definitions["CMAKE_TOOLCHAIN_FILE"] = "conan_paths.cmake" #generated by cmake_path generator
        cmake.definitions["BUILD_TESTING"] = False
        cmake.definitions["BUILD_EXAMPLES"] = False
        cmake.definitions["BUILD_SHARED_LIBS"] = False
        cmake.definitions["SUITESPARSE"] = True if self.options.suitesparse else False
        cmake.definitions["CXSPARSE"] = False
        cmake.definitions["SCHUR_SPECIALIZATIONS"] = False
        cmake.definitions["CUSTOM_BLAS"] = True if self.options.blas == "custom" else False
        cmake.definitions['NO_CMAKE_PACKAGE_REGISTRY'] = True
        cmake.definitions['EIGEN_INCLUDE_DIR:PATH'] = os.path.join(self.deps_cpp_info['eigen'].rootpath, 'include', 'eigen3')
        cmake.definitions['EIGEN_INCLUDE_DIR_HINTS:PATH'] = os.path.join(self.deps_cpp_info['eigen'].rootpath)
        cmake.definitions['GFLAGS_INCLUDE_DIR:PATH'] = os.path.join(self.deps_cpp_info['gflags'].rootpath, 'include')
        cmake.definitions['GFLAGS_LIBRARY:PATH'] = os.path.join(self.deps_cpp_info['gflags'].rootpath, 'lib')
        cmake.definitions['GLOG_INCLUDE_DIR:PATH'] = os.path.join(self.deps_cpp_info['glog'].rootpath, 'include')
        cmake.definitions['GLOG_LIBRARY:PATH'] = os.path.join(self.deps_cpp_info['glog'].rootpath, 'lib')

        if 'cxx11' in self.options and self.options.cxx11:
            cmake.definitions['CMAKE_CXX_STANDARD'] = 11

        if 'fPIC' in self.options and self.options.fPIC:
            cmake.definitions['CMAKE_POSITION_INDEPENDENT_CODE'] = 'ON'

        if tools.os_info.is_linux:
            cmake.definitions['BUILD_SHARED_LIBS:BOOL'] = True if self.options.shared else False

        cmake.configure( source_folder=self.build_folder+'/ceres-solver-'+self.version )
        cmake.build()
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = tools.collect_libs(self)
        if not self.cpp_info.libs:
            raise Exception("No libs collected")
